kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  image: "kindest/node:v1.23.13"
  kubeadmConfigPatches:
    - |
      kind: InitConfiguration
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: "ingress-ready=true"
  extraMounts:
  - containerPath: /var/local-path-provisioner
    hostPath: volumes
  extraPortMappings:
  - containerPort: 31080
    hostPort: 80
    listenAddress: 0.0.0.0
  - containerPort: 31443
    hostPort: 443
    listenAddress: 0.0.0.0
