---
# We require ALL requests to this Gateway to have JWT token
# By default requests with no token will passed this, but with wring tokens will not
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: allow-authenticated
  namespace: mlops
spec:
  selector:
    matchLabels:
      app: istio-ingressgateway  # Default ingressgateway
  jwtRules:
    - issuer: "https://mlops.adimen.tech/realms/mlops"
      jwksUri: "https://mlops.adimen.tech/realms/mlops/protocol/openid-connect/certs"
      forwardOriginalToken: true