apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  meshConfig:
    defaultConfig:
      gatewayTopology:
        numTrustedProxies: 2
    extensionProviders:
      - name: oauth2-proxy
        envoyExtAuthzHttp:
          service: oauth2-proxy.oauth2-proxy.svc.cluster.local
          port: 4180
          includeHeadersInCheck: [ "authorization", "cookie" ]
          headersToUpstreamOnAllow: [ "x-forwarded-access-token", "authorization", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token" ]
          headersToDownstreamOnDeny: [ "content-type", "set-cookie" ]
  components:
    ingressGateways:
      - name: istio-ingressgateway
        k8s:
          overlays:
            - kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.type
                  value: NodePort
                - path: spec.ports.[name:http2].nodePort
                  value: 31080
                - path: spec.ports.[name:https].nodePort
                  value: 31443
