kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: mlops
  namespace: default
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts: ["mlops.adimen.tech"]
            notPaths:
              - /admin/*
              - /resources/*
              - /realms/*
---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: echoserver
  namespace: default
spec:
  selector:
    matchLabels:
      app: echoserver
  jwtRules:
  - issuer: "https://mlops.adimen.tech/realms/mlops"
    forwardOriginalToken: true