apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mlops
  namespace: istio-system
spec:
  commonName: mlops.adimen.tech
  secretName: mlops.adimen.tech-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: letsencrypt-adimen-dns
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - mlops.adimen.tech