apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mlops
  namespace: istio-system
spec:
  commonName: mlops.adimen.local
  secretName: mlops.adimen.local-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - mlops.adimen.local