apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: mlops
  namespace: default
spec:
  hosts:
  - mlops.adimen.tech
  gateways:
  - mlops
  http:
  - match:
    - uri:
        prefix: /admin
    - uri:
        prefix: /realms
    - uri:
        prefix: /resources
    - uri:
        prefix: /js
    route:
    - destination:
        host: keycloak-service.keycloak.svc.cluster.local
        port:
          number: 8080
  - match:
    - uri:
        prefix: /oauth2
    route:
    - destination:
        host: oauth2-proxy.oauth2-proxy.svc.cluster.local
        port:
          number: 4180
  - match:
    - uri:
        prefix: /echo
    route:
      - destination:
          host: echoserver.default.svc.cluster.local
          port:
            number: 4180
  - route:
    - destination:
        host: mlops.apps.svc.cluster.local
        port:
          number: 80