apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- default
namespace: kubeflow
patchesStrategicMerge:
- patches/remove-namespace.yaml
configMapGenerator:
- name: config
  behavior: merge
  literals:
  - USE_ISTIO=true
  - ISTIO_GATEWAY=default/mlops
images:
- name: docker.io/kubeflownotebookswg/notebook-controller
  newName: docker.io/kubeflownotebookswg/notebook-controller
  newTag: v1.7.0-rc.0