---
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: instance-service
  namespace: mlops
spec:
  selector:
    matchLabels:
      app: instance-service
  jwtRules:
  - issuer: "https://mlops.adimen.tech/realms/mlops"
    jwksUri: "https://mlops.adimen.tech/realms/mlops/protocol/openid-connect/certs"
    forwardOriginalToken: true
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: instance-service
  namespace: mlops
spec:
  selector:
    matchLabels:
      app: instance-service
  action: ALLOW
  rules:
    - when:
        - key: request.auth.claims[iss]
          values: [ "https://mlops.adimen.tech/realms/mlops" ]
