apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice
  # TODO(incfly): change to istio-system when the config map is also updated to that namespace.
  namespace: istio-system
  labels:
    app: authservice
spec:
  replicas: 1 # you can scale up productpage as long as session affinity is enabled via a DestinationRule (see ./config/bookinfo-gateway.yaml)
  selector:
    matchLabels:
      app: authservice
  template:
    metadata:
      labels:
        app: authservice
    spec:
      volumes:
        - name: config
          configMap:
            name: authservice-config
      containers:
      - name: authservice # authservice needs to be deployed in the sample Pod as the productpage
        # TODO(incfly): change to a proper project wide container registry.
        image: gcr.io/jianfeih-images-pub/authservice/authservice:0.4.1 # Manually docker pull the latest authservice image from https://github.com/istio-ecosystem/authservice/packages and push it to your own image registry (e.g. Docker Hub), and use it here. (The Github Package Registry does not work with k8s yet until this issue is fixed and released: https://github.com/kubernetes-sigs/kind/issues/870)
        imagePullPolicy: Always
        ports:
          - containerPort: 10003
        volumeMounts:
          - name: config
            mountPath: /etc/authservice
---
apiVersion: v1
kind: Service
metadata:
  name: authservice
  namespace: istio-system
  labels:
    app: authservice
spec:
  ports:
  - port: 10003
    name: grpc
  selector:
    app: authservice
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: authservice-config
  namespace: istio-system
data:
  config.json: |
    {
      "listen_address": "127.0.0.1",
      "listen_port": "10003",
      "log_level": "trace",
      "threads": 8,
      "chains": [
        {
          "name": "idp_filter_chain",
          "filters": [
          {
            "oidc":
              {
                "authorization_uri": "https://keycloak.local/realms/mlops/protocol/openid-connect/auth",
                "token_uri": "https://keycloak.local/realms/mlops/protocol/openid-connect/token",
                "callback_uri": "https://echoserver.local/oauth/callback",
                "jwks_fetcher": {
                  "jwks_uri": "https://keycloak.local/realms/mlops/protocol/openid-connect/certs",
                  "periodic_fetch_interval_sec": 10
                },
                "client_id": "istio-mlops",
                "client_secret": "iuq9NKgODCkn5VSwDTe7LamybKrzf2zw",
                "scopes": [],
                "cookie_name_prefix": "echoserver",
                "id_token": {
                  "preamble": "Bearer",
                  "header": "Authorization"
                },
                "logout": {
                  "path": "/authservice_logout",
                  "redirect_uri": "https://echoserver.local"
                }
              }
            }
          ]
        }
      ]
    }