apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istiocontrolplane
spec:
  meshConfig:
    extensionProviders:
      - name: authservice-grpc
        envoyExtAuthzGrpc:
          service: authservice.istio-system.svc.cluster.local
          port: "10003"
      - name: authservice-http
        envoyExtAuthzHttp:
          service: authservice.istio-system.svc.cluster.local
          port: 10003
          includeRequestHeadersInCheck:
            - cookie
          headersToUpstreamOnAllow:
            - authorization
          headersToDownstreamOnDeny:
            - set-cookie
  components:
    ingressGateways:
      - name: istio-ingressgateway
        k8s:
          overlays:
            - kind: Service
              name: istio-ingressgateway
              patches:
                - path: spec.type
                  value: NodePort
                - path: spec.ports.[name:http2].nodePort
                  value: 31080
                - path: spec.ports.[name:https].nodePort
                  value: 31443
