# We install istio from helm chart in Istio GitHub repo
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: istio
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    tag: 1.17.1
  url: https://github.com/istio/istio.git
