apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echoserver
  namespace: istio-system
spec:
  commonName: echoserver.local
  secretName: echoserver-certs
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - echoserver.local