apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echoserver
spec:
  commonName: echoserver.testing
  secretName: echoserver-certs
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - echoserver.testing