apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth2-proxy-config
  namespace: oauth2-proxy
data:
  alpha-config.yaml: |
    injectRequestHeaders:
      - name: X-Forwarded-Groups
        values:
          - claim: groups
      - name: X-Forwarded-User
        values:
          - claim: user
      - name: X-Forwarded-Email
        values:
          - claim: email
      - name: X-Forwarded-Preferred-Username
        values:
          - claim: preferred_username
