#apiVersion: helm.toolkit.fluxcd.io/v2beta1
#kind: HelmRelease
#metadata:
#  name: oauth2-proxy
#  namespace: oauth2-proxy
#spec:
#  chart:
#    spec:
#      chart: oauth2-proxy
#      sourceRef:
#        kind: HelmRepository
#        name: oauth2-proxy
#        namespace: flux-system
#  interval: 1m0s
#  releaseName: oauth2-proxy
#  targetNamespace: oauth2-proxy
#  values:
#    config:
#      cookieSecret: "MnZ0OVlscmdDVElkMkpnc1F2L1JFeFFDNjk5RVIzQXk="
#      # cookieName: "_oauth2_proxy"    # Name of the cookie that oauth2-proxy creates, if not set defaults to "_oauth2_proxy"
#      configFile: |-
#        email_domains = [ "*" ]        # Restrict to these E-Mail Domains, a wildcard "*" allows any email
#    alphaConfig:
#      enabled: true
#      configData:
#        providers:
#        - clientID: oauth2
#          clientSecret: yytQK33jARdkxtxzdw4htkF4AfesTi7s
#          id: oidc-istio
#          provider: oidc   # We use the generic 'oidc' provider
#          loginURL: https://mlops.adimen.tech/realms/mlops/protocol/openid-connect/auth
#          redeemURL: https://mlops.adimen.tech/realms/mlops/protocol/openid-connect/token
#          profileURL: https://mlops.adimen.tech/realms/mlops/protocol/openid-connect/userinfo
#          validateURL: https://mlops.adimen.tech/realms/mlops/protocol/openid-connect/userinfo
#          scope: "openid email profile groups"
#          oidcConfig:
#            emailClaim: email.  # Name of the clain in JWT containing the E-Mail
#            groupsClaim: groups # Name of the claim in JWT containing the Groups
#            userIDClaim: email  # Name of the claim in JWT containing the User ID
#            skipDiscovery: true # You can try using the well-knwon endpoint directly for auto discovery, here we won't use it
#            issuerURL: https://mlops.adimen.tech/realms/mlops
#            jwksURL: https://mlops.adimen.tech/realms/mlops/protocol/openid-connect/certs
#        upstreamConfig:
#          upstreams:
#            - id: static_200
#              path: /
#              static: true
#              staticCode: 200
#        # Headers that should be added to responses from the proxy
#        injectResponseHeaders:
#          - name: X-Auth-Request-Preferred-Username
#            values:
#              - claim: preferred_username
#          - name: X-Auth-Request-Email
#            values:
#              - claim: email
#          - name: X-Auth-Request-User
#            values:
#              - claim: user
#    extraArgs:
#      cookie-secure: "false"
#      cookie-domain: ".mlops.adimen.tech"
#      cookie-samesite: lax
#      cookie-expire: 12h
#      auth-logging: true
#      request-logging: true
#      standard-logging: true
#      show-debug-on-error: true
#      skip-provider-button: true
#      silence-ping-logging: true
#      whitelist-domain: ".mlops.adimen.tech"
