apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: devops
spec:
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
  interval: 1m0s
  releaseName: cert-manager
  targetNamespace: devops
  values:
    installCRDs: true
    prometheus:
      enabled: false
