apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak
spec:
  commonName: keycloak.local
  secretName: keycloak-certs
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - keycloak.local