apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: mlops
spec:
  keycloakCRName: mlops
  realm:
    id: mlops
    realm: mlops
    displayName: MLOps
    enabled: true
    clients:
      - name: oauth2
