apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-operator
  namespace: istio-operator
spec:
  chart:
    spec:
      chart: ./manifests/charts/istio-operator
      sourceRef:
        kind: GitRepository
        name: istio
        namespace: flux-system
  interval: 1m0s
  releaseName: istio-operator
  targetNamespace: istio-operator
